###
GET http://localhost:3007/api/allUsers

###
GET http://localhost:3007/api/allDoctors


###
POST http://localhost:3007/api/newQuery
Content-Type: application/json

{       
        "name":"dhindhora",
        "mail":"ASU00001",
        "num":1234567890,
        "special":"heyspecial",
        "query":"yoyo"
    }

###
POST http://localhost:3007/api/newDoctor
Content-Type: application/json

{       
        "name":"Doctor",
        "mail":"ASU00001",
        "phno":1234567890,
        "spec":"heyspecial"
    }

###
DELETE http://localhost:3007/api/deleteDoctor/USER15d81664-cf3b-4d1c-b39b-b45dee8653ee
###
DELETE http://localhost:3007/api/deleteQuery/USERa3dd7938-86a0-4aa6-9d0a-b0b6b8e4fe4b